# Generated by Django 4.1.3 on 2023-08-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exaam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='invoice_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_no',
            field=models.CharField(max_length=20),
        ),
    ]
